spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/autoecole_db
    username: sebt-max
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080

servlet:
  multipart:
  enabled: true
  max-file-size: 200MB
  max-request-size: 200MB

link:
  expiration:
    days: 7